#!/bin/bash

IMG_NAME=raspkronos-$RELEASE-$ARCH
PI_GEN_RELEASE=Raspberry Kronos arm64 base
DEPLOY_COMPRESSION=none
LOCALE_DEFAULT=en_US.UTF-8
TARGET_HOSTNAME=raspkronos
KEYBOARD_KEYMAP=us
KEYBOARD_LAYOUT='English (US)'
TIMEZONE_DEFAULT=UTC
FIRST_USER_NAME=kaal
FIRST_USER_PASS=time
WPA_COUNTRY=US
ENABLE_SSH=1
PUBKEY_SSH_FIRST_USER=$(cat authorized_keys)
STAGE_LIST='stage0'

./build.sh
